FROM node:22.12.0-alpine3.21
# Version épinglée : node:22.12.0-alpine3.21

RUN npm install -g pnpm@9

# Utilisateur non-root
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextdev

WORKDIR /app
RUN chown nextdev:nodejs /app

COPY --chown=nextdev:nodejs package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY --chown=nextdev:nodejs . .

USER nextdev
EXPOSE 3000

CMD ["npm", "run", "dev"]
