# ── Stage 1 : Dépendances ────────────────────────────────────────
FROM node:22.12.0-alpine3.21 AS deps

WORKDIR /app

RUN npm install -g pnpm@9

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile


# ── Stage 2 : Build ──────────────────────────────────────────────
FROM node:22.12.0-alpine3.21 AS builder

WORKDIR /app

RUN npm install -g pnpm@9

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN mkdir -p /app/public

RUN pnpm prisma generate

RUN pnpm build
RUN ls -lah .next/
RUN [ -f .next/required-server-files.json ] \
    && echo "required-server-files.json found" \
    || echo "required-server-files.json MISSING"


# ── Stage 3 : Runtime ─────────────────────────────────────────────
FROM node:22.12.0-alpine3.21 AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
