# version: "3.9"

services:

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: engipilot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: engipilot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: engipilot_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: engipilot-redis
    restart: unless-stopped
    command: redis-server --requirepass engipilot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: engipilot-backend
    restart: unless-stopped
    expose:
      - "8080"

  ia-service:
    build: ./ia
    container_name: engipilot-ia
    restart: unless-stopped
    expose:
      - "8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: engipilot-frontend
    restart: unless-stopped
    expose:
      - "3000"

  nginx:
    image: nginx:1.27.3-alpine
    container_name: engipilot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
      - ia-service

volumes:
  postgres_data:
  redis_data: