events {
    worker_connections 1024;
}

http {

    upstream backend {
        server backend:8080;
    }

    upstream frontend {
        server frontend:3000;
    }

    upstream ia {
        server ia-service:8001;
    }

    include /etc/nginx/conf.d/*.conf;
}
